/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kristen
 */
public class EditClient extends javax.swing.JFrame {

    /**
     * Creates new form EditClient
     */
    public EditClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        CNField = new javax.swing.JTextField();
        CCField = new javax.swing.JTextField();
        ExpField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        NameOnCardField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClientEditOut = new javax.swing.JTextArea();
        UpdateName = new javax.swing.JButton();
        UpdateEmail = new javax.swing.JButton();
        UpdatePhone = new javax.swing.JButton();
        UpdateNumber = new javax.swing.JButton();
        UpdateCode = new javax.swing.JButton();
        UpdateExp = new javax.swing.JButton();
        UpdateAddress = new javax.swing.JButton();
        UpdateNOC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Edit client information:");

        jLabel2.setText("Name:");

        jLabel3.setText("Phone:");

        jLabel4.setText("Credit Card Number:");

        jLabel5.setText("Security Code:");

        jLabel6.setText("Expiration (MM/YY):");

        jLabel7.setText("Billing Address:");

        jLabel8.setText("Name On Card:");

        NameField.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                NameFieldComponentAdded(evt);
            }
        });

        PhoneField.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                PhoneFieldComponentAdded(evt);
            }
        });

        CNField.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                CNFieldComponentAdded(evt);
            }
        });

        CCField.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                CCFieldComponentAdded(evt);
            }
        });

        ExpField.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ExpFieldComponentAdded(evt);
            }
        });

        AddressField.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                AddressFieldComponentAdded(evt);
            }
        });

        NameOnCardField.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                NameOnCardFieldComponentAdded(evt);
            }
        });

        jLabel9.setText("Email:");

        EmailField.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                EmailFieldComponentAdded(evt);
            }
        });

        CancelButton.setText("Close");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ClientEditOut.setColumns(20);
        ClientEditOut.setRows(5);
        jScrollPane1.setViewportView(ClientEditOut);

        UpdateName.setText("Update");
        UpdateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateNameActionPerformed(evt);
            }
        });

        UpdateEmail.setText("Update");
        UpdateEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmailActionPerformed(evt);
            }
        });

        UpdatePhone.setText("Update");
        UpdatePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePhoneActionPerformed(evt);
            }
        });

        UpdateNumber.setText("Update");
        UpdateNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateNumberActionPerformed(evt);
            }
        });

        UpdateCode.setText("Update");
        UpdateCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCodeActionPerformed(evt);
            }
        });

        UpdateExp.setText("Update");
        UpdateExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateExpActionPerformed(evt);
            }
        });

        UpdateAddress.setText("Update");
        UpdateAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAddressActionPerformed(evt);
            }
        });

        UpdateNOC.setText("Update");
        UpdateNOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateNOCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addGap(369, 369, 369))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailField)
                                    .addComponent(PhoneField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(CNField)
                                    .addComponent(CCField)
                                    .addComponent(ExpField)
                                    .addComponent(AddressField)
                                    .addComponent(NameOnCardField)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateName)
                            .addComponent(UpdateEmail)
                            .addComponent(UpdatePhone)
                            .addComponent(UpdateNumber)
                            .addComponent(UpdateCode)
                            .addComponent(UpdateExp)
                            .addComponent(UpdateAddress)
                            .addComponent(UpdateNOC))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(UpdateName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(UpdateEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(UpdatePhone))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ExpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateExp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(NameOnCardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateNOC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(CancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void NameFieldComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_NameFieldComponentAdded
        NameField.setText(TourManager.CurrentClient.getName());
    }//GEN-LAST:event_NameFieldComponentAdded

    private void EmailFieldComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_EmailFieldComponentAdded
        EmailField.setText(TourManager.CurrentClient.getEmail());
    }//GEN-LAST:event_EmailFieldComponentAdded

    private void PhoneFieldComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_PhoneFieldComponentAdded
        PhoneField.setText(TourManager.CurrentClient.getPhone());
    }//GEN-LAST:event_PhoneFieldComponentAdded

    private void CNFieldComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_CNFieldComponentAdded
        CNField.setText("" + TourManager.CurrentClient.getCard().getNumber());
    }//GEN-LAST:event_CNFieldComponentAdded

    private void CCFieldComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_CCFieldComponentAdded
        CCField.setText("" + TourManager.CurrentClient.getCard().getCode());
    }//GEN-LAST:event_CCFieldComponentAdded

    private void ExpFieldComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ExpFieldComponentAdded
        ExpField.setText(TourManager.CurrentClient.getCard().getExp());
    }//GEN-LAST:event_ExpFieldComponentAdded

    private void AddressFieldComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_AddressFieldComponentAdded
        AddressField.setText(TourManager.CurrentClient.getCard().getAddress());
    }//GEN-LAST:event_AddressFieldComponentAdded

    private void NameOnCardFieldComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_NameOnCardFieldComponentAdded
        NameOnCardField.setText(TourManager.CurrentClient.getCard().getName());
    }//GEN-LAST:event_NameOnCardFieldComponentAdded

    private void UpdateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateNameActionPerformed
        String name = NameField.getText();
        if (!name.equals("")) {
            TourManager.CurrentClient.setName(name);
        } else {
            ClientEditOut.setText("Error: enter a name to update.");
        }
    }//GEN-LAST:event_UpdateNameActionPerformed

    private void UpdateEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmailActionPerformed
        String email = EmailField.getText();
        if (!email.equals("")) {
            TourManager.CurrentClient.setEmail(email);
        } else {
            ClientEditOut.setText("Error: enter an email to update.");
        }
    }//GEN-LAST:event_UpdateEmailActionPerformed

    private void UpdatePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePhoneActionPerformed
        String phone = PhoneField.getText();
        if (!phone.equals("")) {
            TourManager.CurrentClient.setPhone(phone);
        } else {
            ClientEditOut.setText("Error: enter a phone number to update.");
        }
    }//GEN-LAST:event_UpdatePhoneActionPerformed

    private void UpdateNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateNumberActionPerformed
        try {
            long cn = Long.parseLong(CNField.getText());
            TourManager.CurrentClient.getCard().setNumber(cn);
        } catch (NumberFormatException nfe) {
            ClientEditOut.setText("Error: enter credit card numner with no spaces or other characters.");
        }
    }//GEN-LAST:event_UpdateNumberActionPerformed

    private void UpdateCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCodeActionPerformed
        try {
            int cc = Integer.parseInt(CCField.getText());
            TourManager.CurrentClient.getCard().setCode(cc);
        } catch (NumberFormatException nfe) {
            ClientEditOut.setText("Error: enter security code as an integer.");
        }
    }//GEN-LAST:event_UpdateCodeActionPerformed

    private void UpdateExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateExpActionPerformed
        String exp = ExpField.getText();
        if (!exp.equals("")) {
            TourManager.CurrentClient.getCard().setExp(exp);
        } else {
            ClientEditOut.setText("Error: enter an expiration date to update.");
        }
    }//GEN-LAST:event_UpdateExpActionPerformed

    private void UpdateAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAddressActionPerformed
        String add = AddressField.getText();
        if (!add.equals("")) {
            TourManager.CurrentClient.getCard().setAddress(add);
        } else {
            ClientEditOut.setText("Error: enter an address to update.");
        }
    }//GEN-LAST:event_UpdateAddressActionPerformed

    private void UpdateNOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateNOCActionPerformed
        String noc = NameOnCardField.getText();
        if (!noc.equals("")) {
            TourManager.CurrentClient.getCard().setName(noc);
        } else {
            ClientEditOut.setText("Error: enter a name to update.");
        }
    }//GEN-LAST:event_UpdateNOCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditClient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JTextField CCField;
    private javax.swing.JTextField CNField;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextArea ClientEditOut;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField ExpField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField NameOnCardField;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JButton UpdateAddress;
    private javax.swing.JButton UpdateCode;
    private javax.swing.JButton UpdateEmail;
    private javax.swing.JButton UpdateExp;
    private javax.swing.JButton UpdateNOC;
    private javax.swing.JButton UpdateName;
    private javax.swing.JButton UpdateNumber;
    private javax.swing.JButton UpdatePhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
